<?php

if (!defined('BASEPATH'))
    exit('No direct script access allowed');

class Biodata_model extends CI_Model
{

    public $table = 'biodata';
    public $id = 'uid';
    public $order = 'DESC';

    function __construct()
    {
        parent::__construct();
    }

    // get all
    function get_all()
    {
        $this->db->order_by($this->id, $this->order);
        return $this->db->get($this->table)->result();
    }

    // get data by id
    function get_by_id($id)
    {
        $this->db->where($this->id, $id);
        return $this->db->get($this->table)->row();
    }
    
    // get total rows
    function total_rows($q = NULL) {
        $this->db->like('uid', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('pob', $q);
	$this->db->or_like('dob', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('ktp', $q);
	$this->db->or_like('paspor', $q);
	$this->db->or_like('alamat_ktp', $q);
	$this->db->or_like('alamat_akhir', $q);
	$this->db->or_like('pangkat', $q);
	$this->db->or_like('tmt_pangkat', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->or_like('tmt_jabatan', $q);
	$this->db->or_like('masa_kerja', $q);
	$this->db->or_like('last_update', $q);
	$this->db->from($this->table);
        return $this->db->count_all_results();
    }

    // get data with limit and search
    function get_limit_data($limit, $start = 0, $q = NULL) {
        $this->db->order_by($this->id, $this->order);
        $this->db->like('uid', $q);
	$this->db->or_like('nip', $q);
	$this->db->or_like('nama', $q);
	$this->db->or_like('pob', $q);
	$this->db->or_like('dob', $q);
	$this->db->or_like('agama', $q);
	$this->db->or_like('ktp', $q);
	$this->db->or_like('paspor', $q);
	$this->db->or_like('alamat_ktp', $q);
	$this->db->or_like('alamat_akhir', $q);
	$this->db->or_like('pangkat', $q);
	$this->db->or_like('tmt_pangkat', $q);
	$this->db->or_like('jabatan', $q);
	$this->db->or_like('tmt_jabatan', $q);
	$this->db->or_like('masa_kerja', $q);
	$this->db->or_like('last_update', $q);
	$this->db->limit($limit, $start);
        return $this->db->get($this->table)->result();
    }

    // insert data
    function insert($data)
    {
        $this->db->insert($this->table, $data);
    }

    // update data
    function update($id, $data)
    {
        $this->db->where($this->id, $id);
        $this->db->update($this->table, $data);
    }

    // delete data
    function delete($id)
    {
        $this->db->where($this->id, $id);
        $this->db->delete($this->table);
    }

}

/* End of file Biodata_model.php */
/* Location: ./application/models/Biodata_model.php */
/* Please DO NOT modify this information : */
/* Generated by Harviacode Codeigniter CRUD Generator 2016-11-09 01:13:06 */
/* http://harviacode.com */